[package]
name = "manor_testing"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.2.3"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.16.0", features = ["v4", "fast-rng", "serde"] }
manor = { path = "../manor" }
